In [8]:
import numpy as np
import chainer
# from chainer import cuda, Function, gradient_check, report, training, utils, Variable
# from chainer import datasets, iterators, optimizers, serializers
# from chainer import Link, Chain, ChainList
# import chainer.functions as F
# import chainer.links as L
# from chainer.training import extensions

In [4]:
%matplotlib inline
# import some dependencies
import numpy as np
import matplotlib.pyplot as plt
try:
    import seaborn as sns
    sns.set()
except ImportError:
    pass

import torch
from torch.autograd import Variable

import pyro
import pyro.infer
import pyro.optim
import pyro.distributions as dist

#torch.manual_seed(101)

In [76]:
pv = Variable(torch.Tensor([1.0]))
a = chainer.Variable(np.array([1.0]).astype(np.float32))
b = chainer.Variable(np.array([2.0]).astype(np.float32))

In [77]:
a, b

(variable([ 1.]), variable([ 2.]))

In [79]:
c = 0.5 * (a + b)

In [82]:
c.data

array([ 1.5], dtype=float32)

In [89]:
chainer.functions.log(b)

variable([ 0.69314718])

In [130]:
import scipy
scipy.stats.uniform.logpdf(loc=1, scale=2, x=1.95)

-0.69314718055994529

In [131]:
uniform = pyro.distributions.Uniform(Variable(torch.Tensor([1.0])), Variable(torch.Tensor([3.0])))

In [134]:
x = Variable(torch.Tensor([1.95]))
uniform.log_pdf(x).data[0]

-0.6931471824645996

In [175]:
mu = pyro.distributions.Normal(Variable(torch.Tensor([1.0])), Variable(torch.Tensor([3.0])))
normal = pyro.distributions.Normal(mu, Variable(torch.Tensor([3.0])))

AttributeError: 'Normal' object has no attribute 'size'

In [169]:
normal()

Variable containing:
-4.5245
[torch.FloatTensor of size 1]

In [174]:
np.random.ranf(1)

array([ 0.87868365])

In [144]:
chainer.__version__

'3.3.0'

In [152]:
np.random.rand(1)

array([ 0.64470572])

In [149]:
a + chainer.Variable(np,np.random.random()]) * (b - a)

TypeError: numpy.ndarray or cuda.ndarray are expected.
Actual: <class 'list'>

In [143]:
import random
1 + random.random() * (3-1)

1.9807731522071503

In [123]:
from math import log
log(0)

ValueError: math domain error

In [66]:
import scipy
scipy.stats.uniform.rvs(
            loc=1,
            scale=1
            )

1.8221596327497975

In [70]:
(2-1) ** 2 / 12

0.08333333333333333

In [68]:
scipy.stats.uniform.mean(
            loc=1,
            scale=1
            )

1.5

In [48]:
uniform.sample()

Variable containing:
 1.3761
[torch.FloatTensor of size 1]

In [71]:
mu = Variable(torch.zeros(1))
sigma = Variable(torch.ones(1))
dist.normal(mu, sigma)

Variable containing:
-1.2623
[torch.FloatTensor of size 1]

In [29]:
pv.data.size()

torch.Size([1])

In [28]:
cv.data.size

1

In [7]:
size = 10
x = np.random.randn(size)
data = Variable(torch.Tensor([x]))
data

Variable containing:
-0.7099  0.8365  1.0125 -0.1135 -0.9723 -0.1462  2.4168 -1.1619 -0.7778 -0.0858
[torch.FloatTensor of size 1x10]

In [60]:
data = Variable(torch.Tensor([1.0]))
x = pyro.param('mu', Variable(torch.Tensor([0.0])))
y = pyro.sample('x', dist.normal, mu=x, sigma=Variable(torch.Tensor([1])))
obs = pyro.sample('obs', dist.normal, mu=y, sigma=Variable(torch.Tensor([1])), obs=data)

/Users/y-nagae/.pyenv/versions/miniconda3-4.3.11/envs/ml_env/lib/python3.6/site-packages/pyro/__init__.py:57: RuntimeWarning: trying to observe a value outside of inference at obs
  RuntimeWarning)


In [61]:
obs

Variable containing:
 1
[torch.FloatTensor of size 1]

In [62]:
data

Variable containing:
 1
[torch.FloatTensor of size 1]

In [63]:
x

Variable containing:
-0.8767
[torch.FloatTensor of size 1]

In [64]:
y

Variable containing:
-0.1575
[torch.FloatTensor of size 1]

In [32]:
mu = Variable(torch.zeros(1))
sigma = Variable(torch.ones(1))
n = dist.normal(mu, sigma)

In [41]:
help(pyro.sample)

Help on function sample in module pyro:

sample(name, fn, *args, **kwargs)
    Calls the stochastic function `fn` with additional side-effects depending
    on `name` and the enclosing context (e.g. an inference algorithm).
    See `Intro I <http://pyro.ai/examples/intro_part_i.html>`_ and
    `Intro II <http://pyro.ai/examples/intro_part_ii.html>`_ for a discussion.
    
    :param name: name of sample
    :param fn: distribution class or function
    :param obs: observed datum (optional; should only be used in context of
        inference) optionally specified in kwargs
    :param dict baseline: Optional dictionary of baseline parameters specified
        in kwargs. See inference documentation for details.
    :returns: sample



In [40]:
help(dist.normal)

Help on RandomPrimitive in module pyro.distributions.random_primitive object:

class RandomPrimitive(pyro.distributions.distribution.Distribution)
 |  For help on a RandomPrimitive instance rp, use help(rp.dist_class).
 |  
 |  Method resolution order:
 |      RandomPrimitive
 |      pyro.distributions.distribution.Distribution
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __call__ = sample(self, *args, **kwargs)
 |  
 |  __init__(self, dist_class)
 |      Constructor for base distribution class.
 |      
 |      :param bool reparameterized: Optional argument to override whether
 |          instance should be considered reparameterized (by default, this
 |          is decided by the class).
 |  
 |  analytic_mean(self, *args, **kwargs)
 |      Analytic mean of the distribution, to be implemented by derived classes.
 |      
 |      Note that this is optional, and currently only used for testing distributions.
 |      
 |      :return: Analytic mean.
 |      :rtype: to

In [4]:
# def model():
#     mu = pyro.sample("mu", dist.normal, Variable(torch.zeros(size)), Variable(torch.ones(size)))
#     return pyro.sample("x", dist.normal, mu, Variable(torch.ones(size)))

def model():
    mu = pyro.param("mu", Variable(torch.randn(1), requires_grad=True))
    return pyro.sample("x", dist.normal, mu, Variable(torch.ones(1)))

def guide():
    return None
#     mu_param = pyro.param("mu_param", Variable(torch.randn(size), requires_grad=True))
#     return pyro.sample("mu", dist.delta, mu_param)

# use pyro.condition to constrain model sample site "x" to be equal to some fixed observed data
conditioned_model = pyro.condition(model, data={"x": data})

svi = pyro.infer.SVI(model=conditioned_model, guide=guide, optim=pyro.optim.SGD({"lr": 0.001}), loss="ELBO")

losses = []
for t in range(1000):
    # svi.step is called with whatever arguments model and guide take - in this case, nothing
    losses.append(svi.step())

# to get the value of mu, just call guide
mu_final = guide()

ValueError: The event size for the data and distribution parameters must match.
Expected x.size()[-1] == self.mu.size()[-1], but got 10 vs 1

In [271]:
model()

Variable containing:
-0.8357
[torch.FloatTensor of size 1]